namespace FarmApp.Domain.Core.EnumHelpers
{
    public enum LogType
    {
        Request = 1,
        Response = 2,
        Exception = 3
    }

    public enum ApiMethod
    {
        GetApiMethodRoles = 1,
        PutApiMethodRoles = 2,
        PostApiMethodRoles = 3,
        DeleteApiMethodRoles = 4,
        GetApiMethods = 5,
        PutApiMethods = 6,
        PostApiMethods = 7,
        DeleteApiMethods = 8,
        GetCodeAthTypes = 9,
        PutCodeAthTypes = 10,
        PostCodeAthTypes = 11,
        DeleteCodeAthTypes = 12,
        GetDosageForms = 13,
        PutDosageForms = 14,
        PostDosageForms = 15,
        DeleteDosageForms = 16,
        GetDrugs = 17,
        PutDrugs = 18,
        PostDrugs = 19,
        DeleteDrugs = 20,
        GetPharmacies = 21,
        PutPharmacies = 22,
        PostPharmacies = 23,
        DeletePharmacies = 24,
        GetRegions = 25,
        PutRegions = 26,
        PostRegions = 27,
        DeleteRegions = 28,
        GetRegionTypes = 29,
        PutRegionTypes = 30,
        PostRegionTypes = 31,
        DeleteRegionTypes = 32,
        GetRoles = 33,
        PutPutRoles = 34,
        PostRoles = 35,
        DeleteRoles = 36,
        GetSales = 37,
        PutSales = 38,
        PostSales = 39,
        DeleteSales = 40,
        PostUsersAuthenticate = 41,
        PostUsersRegister = 42,
        GetUsers = 43,
        PutUsers = 44,
        PostUsers = 45,
        GetVendors = 46,
        PutVendors = 47,
        PostVendors = 48,
        DeleteVendors = 49,
        GetLogs = 50,
    }
}
